import fs from 'node:fs';
import path from 'node:path';

/**
 * Astro wants `astro.config.*` and `src/content.config.ts` at its project root. A PaperWhite site
 * has neither: the repo root holds only content, themes, plugins and the YAML config. So the CLI
 * writes a tiny Astro root under `.paperwhite/site/` (ignored by git) and points Astro at it. Both
 * files resolve `@paperwhite/core` by walking up to the site's node_modules.
 */
export function ensureAstroRoot(site: string): string {
  const dir = path.join(site, '.paperwhite', 'site');
  const write = (rel: string, content: string) => {
    const file = path.join(dir, rel);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) fs.writeFileSync(file, content);
  };
  write('package.json', `${JSON.stringify({ name: 'paperwhite-site', private: true, type: 'module' }, null, 2)}\n`);
  write(
    'astro.config.mjs',
    `// Generated by PaperWhite on every dev/build. Edit paperwhite.config.yaml instead.
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import paperwhite from '@paperwhite/core';
import { readUserConfig } from '@paperwhite/core/config/load';

const root = fileURLToPath(new URL('../../', import.meta.url));
export default defineConfig({ integrations: [paperwhite(readUserConfig(root), { root })] });
`,
  );
  write(
    'src/content.config.ts',
    `// Generated by PaperWhite on every dev/build. Edit paperwhite.config.yaml instead.
import { fileURLToPath } from 'node:url';
import { paperwhiteCollections } from '@paperwhite/core/content';
import { readUserConfig } from '@paperwhite/core/config/load';

const root = fileURLToPath(new URL('../../../', import.meta.url));
export const collections = paperwhiteCollections(readUserConfig(root), root);
`,
  );
  write('src/env.d.ts', '/// <reference types="@paperwhite/core/client.d.ts" />\n');
  return dir;
}
