import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import fg from 'fast-glob';
import pc from 'picocolors';
import type { ResolvedConfig } from '../config.ts';
import type { VaultResult } from '../content/vault.ts';

export type Level = 'error' | 'warning' | 'info';

export interface Issue {
  level: Level;
  rule: string;
  page: string;
  message: string;
}

export interface AuditReport {
  pages: number;
  errors: number;
  warnings: number;
  issues: Issue[];
}

function exists(outDir: string, urlPath: string): boolean {
  let p: string;
  try {
    p = decodeURIComponent(urlPath);
  } catch {
    p = urlPath;
  }
  const abs = path.join(outDir, p);
  if (p.endsWith('/')) return fs.existsSync(path.join(abs, 'index.html'));
  return fs.existsSync(abs) || fs.existsSync(path.join(abs, 'index.html')) || fs.existsSync(`${abs}.html`);
}

/** Vault-level checks that need no HTML: unresolved links, alt text, descriptions, orphans. */
export function auditVault(result: VaultResult, config: ResolvedConfig): Issue[] {
  const issues: Issue[] = [];
  for (const u of result.unresolved) issues.push({ level: 'error', rule: 'broken-wikilink', page: u.source, message: `unresolved link → ${u.target}` });
  for (const n of result.notes) {
    const d = n.data;
    for (const img of d.imagesMissingAlt) issues.push({ level: 'error', rule: 'image-alt', page: d.path, message: `image without alt text: ${img}` });
    if (d.autoDescription) issues.push({ level: 'warning', rule: 'missing-description', page: d.path, message: 'no frontmatter description (auto-excerpt used)' });
    if (d.title.length > config.seo.audit.maxTitle)
      issues.push({ level: 'warning', rule: 'title-length', page: d.path, message: `title is ${d.title.length} chars (> ${config.seo.audit.maxTitle})` });
    if (!d.autoDescription && d.description.length > config.seo.audit.maxDescription)
      issues.push({ level: 'warning', rule: 'description-length', page: d.path, message: `description is ${d.description.length} chars (> ${config.seo.audit.maxDescription})` });
    if (d.type === 'post' && d.backlinks.length === 0)
      issues.push({ level: 'info', rule: 'orphan', page: d.path, message: 'no other note links here (orphan)' });
  }
  for (const w of result.warnings) issues.push({ level: 'warning', rule: 'vault', page: w.split(':')[0]!, message: w.slice(w.indexOf(':') + 1).trim() });
  return issues;
}

const attr = (tag: string, name: string): string | undefined => {
  const m = new RegExp(`\\s${name}=(?:"([^"]*)"|'([^']*)'|([^\\s>]+))`, 'i').exec(tag);
  return m ? (m[1] ?? m[2] ?? m[3] ?? '') : undefined;
};
const stripTags = (s: string) => s.replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();

/**
 * HTML-level checks over the build output. Uses lightweight regex scanning (the HTML is
 * generated by PaperWhite, so its shape is known) — a full parse of every page was ~6× slower.
 */
export async function auditHtml(outDir: string, config: ResolvedConfig): Promise<{ pages: number; issues: Issue[] }> {
  const files = await fg('**/*.html', { cwd: outDir, ignore: ['pagefind/**', '_pw/**'] });
  const issues: Issue[] = [];
  const titles = new Map<string, string[]>();
  const existsCache = new Map<string, boolean>();
  let pages = 0;
  await Promise.all(
    files.map(async (rel) => {
      const raw = await fsp.readFile(path.join(outDir, rel), 'utf8');
      if (/<meta http-equiv="refresh"/i.test(raw)) return; // redirect stubs
      pages++;
      const page = `/${rel.replace(/index\.html$/, '')}`;
      // ignore code/script/style content for structural checks
      const html = raw.replace(/<(script|style|pre|template)\b[\s\S]*?<\/\1>/gi, '');
      const noindex = /<meta name="robots" content="[^"]*noindex/.test(html);
      const title = stripTags(/<title>([\s\S]*?)<\/title>/i.exec(html)?.[1] ?? '');
      if (!title) issues.push({ level: 'error', rule: 'missing-title', page, message: 'no <title>' });
      else if (!noindex) {
        // duplicates only matter within one language (cross-locale pages are hreflang alternates)
        const lang = /<html[^>]*\slang="([^"]+)"/.exec(html)?.[1] ?? '';
        const key = `${lang}\u0000${title}`;
        titles.set(key, [...(titles.get(key) ?? []), page]);
      }
      if (!/<meta name="description" content="[^"]+"/.test(html) && !noindex && !rel.startsWith('404'))
        issues.push({ level: 'warning', rule: 'missing-meta-description', page, message: 'no meta description' });
      const h1s = html.match(/<h1[\s>]/gi)?.length ?? 0;
      if (h1s !== 1) issues.push({ level: 'warning', rule: 'h1-count', page, message: `${h1s} <h1> elements (expected 1)` });
      const main = /<main\b[\s\S]*<\/main>/i.exec(html)?.[0] ?? html;
      let prev = 1;
      for (const m of main.matchAll(/<h([1-6])\b([^>]*)>([\s\S]*?)<\/h\1>/gi)) {
        const level = Number(m[1]);
        if (level > prev + 1 && !/class="[^"]*sr-only/.test(m[2]!))
          issues.push({ level: 'warning', rule: 'heading-order', page, message: `<h${level}> "${stripTags(m[3]!).slice(0, 40)}" skips a level after <h${prev}>` });
        prev = level;
      }
      for (const m of html.matchAll(/<img\b[^>]*>/gi)) {
        if (attr(m[0], 'alt') === undefined) issues.push({ level: 'error', rule: 'image-alt', page, message: `<img src="${attr(m[0], 'src')}"> has no alt attribute` });
      }
      const checked = new Set<string>();
      for (const m of html.matchAll(/<a\b[^>]*\shref="([^"]*)"/gi)) {
        const href = m[1]!.replace(/&amp;/g, '&');
        if (!href.startsWith('/') || href.startsWith('//')) continue;
        const target = href.split('#')[0]!.split('?')[0]!;
        if (!target || checked.has(target) || target.startsWith('/_pw/') || target.startsWith('/pagefind/')) continue;
        checked.add(target);
        let ok = existsCache.get(target);
        if (ok === undefined) existsCache.set(target, (ok = exists(outDir, target)));
        if (!ok) issues.push({ level: 'error', rule: 'broken-link', page, message: `broken internal link → ${href}` });
      }
    }),
  );
  for (const [key, list] of titles) {
    const title = key.split('\u0000')[1];
    if (list.length > 1) issues.push({ level: 'error', rule: 'duplicate-title', page: list.sort().join(', '), message: `duplicate <title> "${title}"` });
  }
  void config;
  return { pages, issues };
}

export async function runAudit(outDir: string, config: ResolvedConfig, vault?: VaultResult): Promise<AuditReport> {
  const html = await auditHtml(outDir, config);
  const issues = [...(vault ? auditVault(vault, config) : []), ...html.issues];
  return {
    pages: html.pages,
    errors: issues.filter((i) => i.level === 'error').length,
    warnings: issues.filter((i) => i.level === 'warning').length,
    issues,
  };
}

export function printAudit(report: AuditReport, logger: { info(m: string): void; warn(m: string): void; error(m: string): void }) {
  const icon = { error: pc.red('✖'), warning: pc.yellow('▲'), info: pc.dim('·') };
  const byRule = new Map<string, Issue[]>();
  for (const i of report.issues.filter((x) => x.level !== 'info')) byRule.set(`${i.level}:${i.rule}`, [...(byRule.get(`${i.level}:${i.rule}`) ?? []), i]);
  for (const list of byRule.values()) {
    const shown = list[0]!.level === 'error' ? list : list.slice(0, 3);
    for (const i of shown) {
      const line = `${icon[i.level]} ${pc.bold(i.rule)} ${pc.dim(i.page)} — ${i.message}`;
      if (i.level === 'error') logger.error(line);
      else logger.warn(line);
    }
    if (list.length > shown.length) logger.warn(`${icon.warning} ${pc.bold(list[0]!.rule)} … and ${list.length - shown.length} more (see .paperwhite/audit.json)`);
  }
  const info = report.issues.filter((i) => i.level === 'info').length;
  logger.info(`SEO audit: ${report.pages} pages · ${report.errors} errors · ${report.warnings} warnings · ${info} notes`);
}
